import '@servicenow/sdk/global'
import { ClientScript } from '@servicenow/sdk/core'

//creates a client script that pops up 'Table loaded successfully!!' message everytime todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'Demo Client Script',
    table: 'x_648117_ide_san_0_todo',
    active: true,
    appliesExtended: false,
    global: true,
    uiType: 'all',
    description: 'Custom client script generated by Now SDK',
    isolateScript: false,
    type: 'onLoad',
    script: Now.include('./client/demo-cs.js'),
})